import { describe, expect, it, vi } from 'vitest'
import { renderToStaticMarkup } from 'react-dom/server'

import { ThemeSwitcher } from './ThemeSwitcher'

const mockSetTheme = vi.fn()
const mockSetMode = vi.fn()
const mockSetFontOverride = vi.fn()

vi.mock('@/stores/themeStore', () => ({
  AVAILABLE_FONTS: [
    {
      id: 'plus-jakarta-sans',
      name: 'Plus Jakarta Sans',
      family: '"Plus Jakarta Sans", system-ui, sans-serif',
      category: 'sans',
    },
  ],
  useTheme: () => ({
    themes: [
      {
        id: 'frond',
        name: 'Frond',
        description: 'Brand theme preview',
        author: 'Niamoto',
        inspiration: 'Test fixture',
        tags: ['brand'],
        style: 'brand',
        fontsUrl: '/fonts/fonts.css',
        preview: {
          primary: '#2d7a3a',
          secondary: '#7c8aa0',
          accent: '#5bbf6a',
          background: '#ffffff',
          fontDisplay: '"Plus Jakarta Sans", system-ui, sans-serif',
          borderRadius: '16px',
        },
        light: {
          background: '#f7f8f5',
          foreground: '#112233',
          card: '#ffffff',
          cardForeground: '#112233',
          popover: '#ffffff',
          popoverForeground: '#112233',
          primary: '#2d7a3a',
          primaryForeground: '#ffffff',
          secondary: '#c8d2dd',
          secondaryForeground: '#112233',
          muted: '#eef2f6',
          mutedForeground: '#667788',
          accent: '#dbe7dd',
          accentForeground: '#112233',
          destructive: '#aa3344',
          destructiveForeground: '#ffffff',
          success: '#2d7a3a',
          successForeground: '#ffffff',
          warning: '#c9902f',
          warningForeground: '#112233',
          info: '#3366aa',
          infoForeground: '#ffffff',
          border: '#dde3e8',
          input: '#dde3e8',
          ring: '#2d7a3a',
          chart1: '#2d7a3a',
          chart2: '#5bbf6a',
          chart3: '#3366aa',
          chart4: '#c9902f',
          chart5: '#7c8aa0',
          dataSourcePrimary: '#2d7a3a',
          dataSourcePrimaryForeground: '#ffffff',
          dataSourceSecondary: '#3366aa',
          dataSourceSecondaryForeground: '#ffffff',
          sidebar: '#eef2f6',
          sidebarForeground: '#112233',
          sidebarPrimary: '#2d7a3a',
          sidebarPrimaryForeground: '#ffffff',
          sidebarAccent: '#dbe7dd',
          sidebarAccentForeground: '#112233',
          sidebarBorder: '#dde3e8',
          sidebarRing: '#2d7a3a',
          fontDisplay: '"Plus Jakarta Sans", system-ui, sans-serif',
          fontBody: '"Plus Jakarta Sans", system-ui, sans-serif',
          fontMono: '"JetBrains Mono", monospace',
          radiusNone: '0',
          radiusSm: '8px',
          radiusMd: '12px',
          radiusLg: '16px',
          radiusXl: '20px',
          radiusFull: '9999px',
          borderWidth: '1px',
          shadowNone: 'none',
          shadowSm: '0 1px 2px rgb(0 0 0 / 0.05)',
          shadowMd: '0 4px 12px rgb(0 0 0 / 0.08)',
          shadowLg: '0 8px 24px rgb(0 0 0 / 0.12)',
          shadowXl: '0 16px 40px rgb(0 0 0 / 0.16)',
          backdropBlur: '8px',
          surfaceOpacity: '0.85',
          transitionFast: '150ms',
          transitionBase: '220ms',
          transitionSlow: '320ms',
          transitionEasing: 'cubic-bezier(0.4, 0, 0.2, 1)',
        },
        dark: {
          background: '#05070b',
          foreground: '#ecf3ef',
          card: '#11151c',
          cardForeground: '#ecf3ef',
          popover: '#11151c',
          popoverForeground: '#ecf3ef',
          primary: '#7ad388',
          primaryForeground: '#08110b',
          secondary: '#314255',
          secondaryForeground: '#ecf3ef',
          muted: '#18202c',
          mutedForeground: '#a5b1bf',
          accent: '#1d2933',
          accentForeground: '#ecf3ef',
          destructive: '#f07a8a',
          destructiveForeground: '#08110b',
          success: '#7ad388',
          successForeground: '#08110b',
          warning: '#f0c26d',
          warningForeground: '#08110b',
          info: '#79aef8',
          infoForeground: '#08110b',
          border: '#243244',
          input: '#243244',
          ring: '#7ad388',
          chart1: '#7ad388',
          chart2: '#79aef8',
          chart3: '#f0c26d',
          chart4: '#4f6c8f',
          chart5: '#a5b1bf',
          dataSourcePrimary: '#7ad388',
          dataSourcePrimaryForeground: '#08110b',
          dataSourceSecondary: '#79aef8',
          dataSourceSecondaryForeground: '#08110b',
          sidebar: '#0f141b',
          sidebarForeground: '#ecf3ef',
          sidebarPrimary: '#7ad388',
          sidebarPrimaryForeground: '#08110b',
          sidebarAccent: '#1d2933',
          sidebarAccentForeground: '#ecf3ef',
          sidebarBorder: '#243244',
          sidebarRing: '#7ad388',
          fontDisplay: '"Plus Jakarta Sans", system-ui, sans-serif',
          fontBody: '"Plus Jakarta Sans", system-ui, sans-serif',
          fontMono: '"JetBrains Mono", monospace',
          radiusNone: '0',
          radiusSm: '8px',
          radiusMd: '12px',
          radiusLg: '16px',
          radiusXl: '20px',
          radiusFull: '9999px',
          borderWidth: '1px',
          shadowNone: 'none',
          shadowSm: '0 1px 2px rgb(0 0 0 / 0.2)',
          shadowMd: '0 4px 12px rgb(0 0 0 / 0.28)',
          shadowLg: '0 8px 24px rgb(0 0 0 / 0.36)',
          shadowXl: '0 16px 40px rgb(0 0 0 / 0.44)',
          backdropBlur: '8px',
          surfaceOpacity: '0.8',
          transitionFast: '150ms',
          transitionBase: '220ms',
          transitionSlow: '320ms',
          transitionEasing: 'cubic-bezier(0.4, 0, 0.2, 1)',
        },
      },
    ],
    themeId: 'frond',
    mode: 'dark',
    resolvedMode: 'dark',
    currentTheme: null,
    setTheme: mockSetTheme,
    setMode: mockSetMode,
    setFontOverride: mockSetFontOverride,
    fontOverride: null,
  }),
}))

vi.mock('@/themes', () => ({
  loadThemeFonts: vi.fn(),
}))

describe('ThemeSwitcher', () => {
  it('renders theme previews with dark tokens when dark mode is active', () => {
    const html = renderToStaticMarkup(<ThemeSwitcher columns={2} />)

    expect(html).toContain('background-color:#11151c')
    expect(html).toContain('background-color:#05070b')
    expect(html).toContain('color:#7ad388')
    expect(html).toContain('color:#a5b1bf')
  })
})
