repos:

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
    hooks:
    -   id: ruff
        args: [ --fix ]
    -   id: ruff-format

# Vérification des types avec MyPy
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.8.0
#     hooks:
#     -   id: mypy
#         args: [--config-file=mypy.ini, --no-strict-optional, --ignore-missing-imports]
#         additional_dependencies:
#           - types-click>=7.1.8
#           - types-tabulate>=0.9.0.3
#           - types-pluggy>=1.2.0.2
#           - pandas-stubs>=2.1.1.230928
#           - types-pyyaml>=6.0.12.20240311
#           - types-shapely>=2.0.0

# Vérifications de sécurité
# -   repo: https://github.com/PyCQA/bandit
#     rev: 1.7.7
#     hooks:
#     -   id: bandit
#         args: ["-c", "pyproject.toml"]
#         additional_dependencies: ["bandit[toml]"]

# Vérifications générales
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml  # Vérifie la syntaxe du pyproject.toml
    -   id: check-added-large-files
        args: ['--maxkb=5000']
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: detect-private-key

# Hook local pour générer les requirements
-   repo: local
    hooks:
    -   id: generate-requirements
        name: Generate Requirements Files
        entry: python scripts/generate_requirements.py
        language: python
