repos:

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.2
    hooks:
    -   id: ruff
        args: [ --fix ]
    -   id: ruff-format

-   repo: https://github.com/python-poetry/poetry
    rev: 2.0.1
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
    -   id: poetry-install

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.7.0
#     hooks:
#     -   id: mypy
#         args: [--config-file=mypy.ini, --no-strict-optional, --ignore-missing-imports, --follow-imports=skip]
#         additional_dependencies: [types-click, types-tabulate, types-pluggy, data-science-types]