- id: generate-requirements
  name: Generate Requirements Files
  description: Generate requirements.txt and requirements-dev.txt from pyproject.toml
  entry: python scripts/generate_requirements.py
  language: python
  pass_filenames: false
  files: ^pyproject\.toml$
  stages: [commit]
