- id: generate-requirements
  name: Generate Requirements Files
  description: Generate requirements.txt and dev-requirements.txt from pyproject.toml
  entry: python scripts/generate_requirements.py
  language: python
  types: [python]
  pass_filenames: false
  files: ^(pyproject\.toml|requirements\.txt|dev-requirements\.txt)$
