version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    poetry: "1.7.1"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

python:
  install:
    - method: poetry
      path: .

formats:
  - pdf
  - epub
