version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

poetry:
  version: "2.0.1"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

python:
  install:
    - method: poetry
      path: .

formats:
  - pdf
  - epub
