database:
  path: db/niamoto.db
logs:
  path: logs
exports:
  web: exports/web # web root directory
  api: exports/api # api root directory
plugins:
  path: plugins # Path to the project plugins directory
templates:
  path: templates # Path to the project templates directory
