# Taxonomy extracted from occurrences
taxonomy:
  path: imports/occurrences.csv  # Path to occurrences file
  hierarchy:
    levels:
    - name: family
      column: tax_fam
    - name: genus
      column: tax_gen
    - name: species
      column: tax_sp_level
    - name: infra
      column: tax_infra_level
    taxon_id_column: idtax_f  # Column containing taxon ID
  api_enrichment:
    enabled: true
    plugin: "api_taxonomy_enricher"
    api_url: "https://api.endemia.nc/v1/taxons"
    # Authentification par clé API dans l'en-tête
    auth_method: "api_key"
    auth_params:
      key: "your_api_key"  # Votre clé API
      location: "header"  # Dans l'en-tête HTTP
      name: "apiKey"      # Nom exact de l'en-tête
    query_params:
      section: "flore"
      maxitem: "1"
      excludes: "meta,links"  # Exclure les métadonnées inutiles
      includes: "images"  # Inclure les images

    query_field: "full_name"  # Field to use for querying the API
    # Limites et optimisations
    rate_limit: 2.0
    cache_results: true
    # Mapping des champs prioritaires mentionnés
    response_mapping:
      # Champs prioritaires
      id_endemia: "id"
      id_florical: "id_florical"
      endemia_url: "endemia_url"
      endemic: "endemique"
      protected: "protected"
      protected_provnord: "protected_provnord"
      protected_provsud: "protected_provsud"
      redlist: "redlist"
      redlist_cat: "categorie_uicn"

      # Champs d'image
      image_small_thumb: "image.small_thumb"
      image_big_thumb: "image.big_thumb"
      image_auteur: "image.auteur"

      images: "images"  # Champ pour les images multiples

plots:
  type: csv
  path: imports/plots.csv
  identifier: id_plot  # Plot identifier field in CSV
  locality_field: plot_name  # Locality name field that will populate locality in plot_ref
  location_field: geo_pt  # Geometry field
  link_field: plot_id  # Field to use in plot_ref for linking
  occurrence_link_field: plot_id  # Field to use in occurrences for linking
  hierarchy:
    enabled: true
    levels:
    - method
    - country
    - plot_name
    aggregate_geometry: true  # Aggregate geometries for parent levels


occurrences:
  type: csv
  path: imports/occurrences.csv
  identifier: id_occurrence
  location_field: geo_pt

plot_stats:
  type: csv
  path: "imports/raw_plot_stats.csv"
  identifier: "plot_id"

shape_stats:
  type: csv
  path: "imports/raw_shape_stats.csv"
  identifier: "id"

# Multiple shapes (administrative areas, substrates, etc.)
shapes:
  - type: grid
    path: imports/shapes/grid.zip
    name_field: name
    id_field: id_grid  # Field containing unique shape ID

  - type: provinces
    path: imports/shapes/provinces.zip
    name_field: nom
    id_field: code_province

  - type: communes
    path: imports/shapes/communes.zip
    name_field: nom
    id_field: code_commune

  - type: protected_areas
    path: imports/shapes/protected_areas.zip
    name_field: libelle
    id_field: id_area

  - type: substrates
    path: imports/shapes/substrate.gpkg
    name_field: label
    id_field: substrate_id

# Layers: vectors, rasters...
layers:
  - name: "forest_cover"
    type: vector
    format: shapefile
    path: "imports/layers/amap_carto_3k_20240715/amap_carto_3k_20240715.shp"
    description: "Forest cover layer"

  - name: "elevation"
    type: raster
    path: "imports/layers/mnt100_epsg3163.tif"
    description: "Digital elevation model"

  - name: "rainfall"
    type: raster
    path: "imports/layers/rainfall_epsg3163.tif"
    description: "Annual rainfall distribution"

  - name: "holdridge"
    type: raster
    path: "imports/layers/amap_raster_holdridge_nc.tif"
    description: "Holdridge"
