import {
  Activity,
  Archive,
  Award,
  BarChart3,
  Bird,
  BookOpen,
  Bug,
  Calendar,
  Clock,
  Cloud,
  Compass,
  Database,
  Download,
  Droplets,
  ExternalLink,
  Eye,
  FileText,
  Files,
  Fish,
  FlaskConical,
  Flower2,
  Folder,
  Globe,
  GraduationCap,
  Grid3X3,
  Heart,
  HelpCircle,
  Home,
  Info,
  Layers,
  LayoutGrid,
  Leaf,
  Link,
  Map,
  MapPin,
  Microscope,
  Mountain,
  Navigation,
  PieChart,
  Search,
  Settings,
  Sprout,
  Star,
  Sun,
  Target,
  TrendingUp,
  TreeDeciduous,
  TreePine,
  Upload,
  User,
  Users,
  Waves,
  Zap,
  type LucideIcon,
} from 'lucide-react'

export const ICON_REGISTRY: Record<string, LucideIcon> = {
  leaf: Leaf,
  'tree-pine': TreePine,
  'tree-deciduous': TreeDeciduous,
  flower: Flower2,
  sprout: Sprout,
  mountain: Mountain,
  waves: Waves,
  sun: Sun,
  cloud: Cloud,
  droplets: Droplets,
  bird: Bird,
  bug: Bug,
  fish: Fish,
  'bar-chart': BarChart3,
  'trending-up': TrendingUp,
  'pie-chart': PieChart,
  activity: Activity,
  target: Target,
  gauge: Zap,
  map: Map,
  'map-pin': MapPin,
  globe: Globe,
  compass: Compass,
  navigation: Navigation,
  database: Database,
  folder: Folder,
  'file-text': FileText,
  files: Files,
  archive: Archive,
  search: Search,
  microscope: Microscope,
  flask: FlaskConical,
  book: BookOpen,
  graduation: GraduationCap,
  eye: Eye,
  info: Info,
  help: HelpCircle,
  settings: Settings,
  users: Users,
  user: User,
  home: Home,
  link: Link,
  'external-link': ExternalLink,
  download: Download,
  upload: Upload,
  layers: Layers,
  'grid-3x3': Grid3X3,
  'layout-grid': LayoutGrid,
  calendar: Calendar,
  clock: Clock,
  zap: Zap,
  star: Star,
  heart: Heart,
  award: Award,
}

export function renderLucideIcon(name: string, className?: string) {
  const Icon = ICON_REGISTRY[name]
  if (!Icon) return null
  return <Icon className={className} />
}
