"""Tests for scripts/build/generate_requirements.py."""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest


SCRIPT = (
    Path(__file__).resolve().parents[2]
    / "scripts"
    / "build"
    / "generate_requirements.py"
)


def _load_module():
    spec = importlib.util.spec_from_file_location("generate_requirements", SCRIPT)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules["generate_requirements"] = module
    spec.loader.exec_module(module)
    return module


def test_add_platform_markers_marks_uvloop_as_non_windows(tmp_path):
    requirements = tmp_path / "requirements.txt"
    requirements.write_text(
        "\n".join(
            [
                "uvicorn==0.42.0",
                "uvloop==0.21.0",
                "    # via uvicorn",
            ]
        )
        + "\n",
        encoding="utf-8",
    )

    module = _load_module()
    module.add_platform_markers(requirements)

    assert 'uvloop==0.21.0 ; sys_platform != "win32"' in requirements.read_text(
        encoding="utf-8"
    )


def test_add_platform_markers_keeps_existing_marker(tmp_path):
    requirements = tmp_path / "requirements.txt"
    requirements.write_text(
        'uvloop==0.21.0 ; sys_platform != "win32"\n',
        encoding="utf-8",
    )

    module = _load_module()
    module.add_platform_markers(requirements)

    assert (
        requirements.read_text(encoding="utf-8")
        == 'uvloop==0.21.0 ; sys_platform != "win32"\n'
    )


def test_uv_resolution_args_includes_lock_cutoffs(tmp_path):
    lock_file = tmp_path / "uv.lock"
    lock_file.write_text(
        """
[options]
exclude-newer = "2026-05-14T16:00:51.329945Z"

[options.exclude-newer-package]
duckdb = "2026-05-21T00:00:00Z"
""".lstrip(),
        encoding="utf-8",
    )

    module = _load_module()

    assert module.uv_resolution_args(lock_file) == [
        "--exclude-newer",
        "2026-05-14T16:00:51.329945Z",
        "--exclude-newer-package",
        "duckdb=2026-05-21T00:00:00Z",
    ]


def test_compile_requirements_file_preserves_existing_output_on_failure(
    tmp_path, monkeypatch
):
    output_file = tmp_path / "dev-requirements.txt"
    output_file.write_text("existing-package==1.0.0\n", encoding="utf-8")

    module = _load_module()

    def failing_run_command(cmd):
        output_arg = cmd[cmd.index("-o") + 1]
        Path(output_arg).write_text("", encoding="utf-8")
        raise SystemExit(1)

    monkeypatch.setattr(module, "run_command", failing_run_command)

    with pytest.raises(SystemExit):
        module.compile_requirements_file(
            [
                "uv",
                "pip",
                "compile",
                "pyproject.toml",
                "--group",
                "dev",
                "-o",
                "dev-requirements.txt",
            ],
            output_file,
        )

    assert output_file.read_text(encoding="utf-8") == "existing-package==1.0.0\n"


def test_compile_requirements_file_restores_stable_output_path_in_header(
    tmp_path, monkeypatch
):
    output_file = tmp_path / "requirements.txt"
    module = _load_module()

    def successful_run_command(cmd):
        output_arg = cmd[cmd.index("-o") + 1]
        Path(output_arg).write_text(
            (
                "# This file was autogenerated by uv via the following command:\n"
                f"#    uv pip compile pyproject.toml -o {output_arg}\n"
                "package==1.0.0\n"
            ),
            encoding="utf-8",
        )

    monkeypatch.setattr(module, "run_command", successful_run_command)

    module.compile_requirements_file(
        [
            "uv",
            "pip",
            "compile",
            "pyproject.toml",
            "-o",
            "requirements.txt",
        ],
        output_file,
    )

    generated = output_file.read_text(encoding="utf-8")

    assert "-o requirements.txt" in generated
    assert str(output_file.parent) not in generated
